config/routes.rb
Rails.application.routes.draw do
  get  'inquiries/index'    => 'inquiries#index'
  post 'inquiries/confirm'  => 'inquiries#confirm'
  post 'inquiries/thanks'   => 'inquiries#thanks'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  # user
  namespace :user do
    resources :users
    resources :ramen_noodles do
      resources :ramen_noodle_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      get :search, on: :collection
    end
  end

  root "user/homes#top"
  get  "ramen_noodles"  => "ramen_noodles#index"
  get  "about"          => "user/homes#about"

  # admin
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :ramen_noodles, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_noodle
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => '名前を入力してください' }
  validates :email, :presence => { :message => 'メールアドレスを入力してください' }

  require 'active_model'

  class Person
    include ActiveModel::Validations
  end
end

app/models/ramen_noodle.rb
class RamenNoodle < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  attachment :image
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, :address, :name, :price, :body, :image, presence: true
  validates :price, numericality: true
end

app/models/ramen_noodle_comment.rb
class RamenNoodleComment < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_noodle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ramen_noodles, dependent: :destroy
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, :gender, :age, presence: true
  validates :age, numericality: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  # トップページ
  def top
  end
end

app/controllers/admin/ramen_noodles_controller.rb
class Admin::RamenNoodlesController < ApplicationController
  before_action :authenticate_admin!

  # レビュー一覧ページ
  def index
    @ramen_noodles = RamenNoodle.page(params[:page]).reverse_order
  end

  # レビュー詳細ページ
  def show
    @ramen_noodle = RamenNoodle.find(params[:id])
  end

  # レビュー削除アクション
  def destroy
    @ramen_noodle = RamenNoodle.find(params[:id])
    @ramen_noodle.destroy
    redirect_to admin_ramen_noodles_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  # ユーザー一覧ページ
  def index
    @users = User.page(params[:page]).per(10)
  end

  # ユーザー詳細ページ
  def show
    @user = User.find(params[:id])
  end

  # ユーザー削除アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age])
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  # お問い合わせ画面
  def index
    @inquiry = Inquiry.new
    render 'index'
  end

  # お問い合わせ確認画面
  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      render 'confirm'
    else
      render 'index'
    end
  end

  # お問い合わせ完了通知画面
  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
    render 'thanks'
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # トップページ
  def top
    @all_ranks = RamenNoodle.find(Favorite.group(:ramen_noodle_id).order('count(ramen_noodle_id) desc').limit(3).pluck(:ramen_noodle_id))
  end

  # aboutページ
  def about
  end
end

app/controllers/user/ramen_noodles_controller.rb
class User::RamenNoodlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ramen_noodle, only: [:show, :edit, :update, :destroy]

  # レビュー新規投稿ページ
  def new
    @ramen_noodle = RamenNoodle.new
  end

  # レビュー投稿アクション
  def create
    @ramen_noodle = RamenNoodle.new(ramen_noodle_params)
    @ramen_noodle.user_id = current_user.id
    if @ramen_noodle.save(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle.id), notice: "レビューを投稿しました！"
    else
      @ramen_noodles = RamenNoodle.all
      render 'new'
    end
  end

  # レビュー一覧ページ
  def index
    @ramen_noodles = RamenNoodle.page(params[:page]).reverse_order
  end

  # レビュー詳細ページ
  def show
    @ramen_noodle_comment = RamenNoodleComment.new
  end

  # レビュー更新ページ
  def edit
    @user = @ramen_noodle.user
  end

  # レビュー更新アクション
  def update
    if @ramen_noodle.update(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle), notice: "レビュー内容を更新しました！"
    else
      render "edit"
    end
  end

  # レビュー削除アクション
  def destroy
    @ramen_noodle.destroy
    redirect_to user_ramen_noodles_path
  end

  # レビュー検索ページ
  def search
    if params[:address].present?
      @ramen_noodles = RamenNoodle.where('address LIKE ?', "%#{params[:address]}%")
    else
      @ramen_noodles = RamenNoodle.none
    end
  end

  private

  def ramen_noodle_params
    params.require(:ramen_noodle).permit(:title, :address, :image, :name, :price, :body)
  end

  def set_ramen_noodle
    @ramen_noodle = RamenNoodle.find(params[:id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  # マイページ
  def show
    @user = current_user
    @ramen_noodles = @user.ramen_noodles.page(params[:page]).reverse_order
  end

  # 登録情報編集ページ
  def edit
    @user = current_user
  end

  # 更新アクション
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to user_user_path
    else
      render "edit"
    end
  end

  # 退会アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/ramen_noodles_helper.rb
module Admin::RamenNoodlesHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/ramen_noodles_helper.rb
module User::RamenNoodlesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/views/admin/ramen_noodles/index.html.erb
<div class="container">
	<div class="row">

		<h2>レビュー一覧</h2>
		<table class="table table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>店名</th>
					<th>商品名</th>
					<th>ユーザー</th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<% @ramen_noodles.each do |ramen_noodle| %>
					<td><%= attachment_image_tag ramen_noodle, :image, :fill, 250, 250, fallback: "no_image.png", size:"250x250" %></td>
					<td><%= ramen_noodle.title %></td>
					<td><%= link_to ramen_noodle.name, admin_ramen_noodle_path(ramen_noodle) %></td>
					<td><%= ramen_noodle.user.name %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>

<%= paginate @ramen_noodles %>

app/views/admin/ramen_noodles/show.html.erb
<div class="container">
	<div class="row">
		<h2>レビュー詳細</h2>

		<div class="col-xs-4">
			<%= attachment_image_tag(@ramen_noodle, :image, :fill, 380, 380) %>
		</div>

		<div class="col-xs-8">
			<table class="table table-bordered">
				<tbody>
					<tr>
						<td class="active">店名</td>
						<td><%= @ramen_noodle.title %></td>
					</tr>

					<tr>
						<td class="active">住所</td>
						<td>
							<%= @ramen_noodle.address %>
							<script type="text/javascript">
								function initMap() {
									var test ={lat: <%= @ramen_noodle.latitude %>, lng: <%= @ramen_noodle.longitude %>};
									var map = new google.maps.Map(document.getElementById('map'), {
										zoom: 15,
										center: test
									});
									var transitLayer = new google.maps.TransitLayer();
									transitLayer.setMap(map);

									var contentString = '住所:<%= @ramen_noodle.address %>';
									var infowindow = new google.maps.InfoWindow({
										content: contentString
									});

									var marker = new google.maps.Marker({
										position:test,
										map: map,
										title: contentString
									});

									marker.addListener('click', function() {
										infowindow.open(map, marker);
									});
								}
							</script>

							<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
							</script>

							<style type="text/css">
								#map { height: 250px; width: 100%;}
							</style>

							<div id="map"></div>
						</td>
					</tr>

					<tr>
						<td class="active col-xs-3 col-sm-4">商品名</td>
						<td><%= @ramen_noodle.name %></td>
					</tr>

					<tr>
						<td class="active">値段</td>
						<td><%= @ramen_noodle.price %>円(税込)</td>
					</tr>

					<tr>
						<td class="active">レビュー</td>
						<td><%= @ramen_noodle.body %></td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="pull-right">
			<%= link_to 'レビューを削除する', admin_ramen_noodle_path(@ramen_noodle.id),method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %>
		</div>
	</div>
</div>