config/routes.rb
Rails.application.routes.draw do
  get  'inquiries/index'    => 'inquiries#index'
  post 'inquiries/confirm'  => 'inquiries#confirm'
  post 'inquiries/thanks'   => 'inquiries#thanks'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  # user
  namespace :user do
    resources :users
    resources :ramen_noodles do
      resources :ramen_noodle_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      get :search, on: :collection
    end
  end

  root "user/homes#top"
  get  "ramen_noodles"  => "ramen_noodles#index"
  get  "about"          => "user/homes#about"

  # admin
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :ramen_noodles, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ramen_noodles, dependent: :destroy
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, :gender, :age, presence: true
  validates :age, numericality: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  # ユーザー一覧ページ
  def index
    @users = User.page(params[:page]).per(10)
  end

  # ユーザー詳細ページ
  def show
    @user = User.find(params[:id])
  end

  # ユーザー削除アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  # いいねを付ける
  def create
    ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    favorite = current_user.favorites.new(ramen_noodle_id: ramen_noodle.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  # いいねの取り消し
  def destroy
    ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    favorite = current_user.favorites.find_by(ramen_noodle_id: ramen_noodle.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # トップページ
  def top
    @all_ranks = RamenNoodle.find(Favorite.group(:ramen_noodle_id).order('count(ramen_noodle_id) desc').limit(3).pluck(:ramen_noodle_id))
  end

  # aboutページ
  def about
  end
end

app/controllers/user/ramen_noodle_comments_controller.rb
class User::RamenNoodleCommentsController < ApplicationController
  before_action :authenticate_user!

  # コメントの作成
  def create
    @ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    comment = current_user.ramen_noodle_comments.new(ramen_noodle_comment_params)
    comment.ramen_noodle_id = @ramen_noodle.id
    comment.save
    redirect_to user_ramen_noodle_path(@ramen_noodle)
  end

  # コメントの削除
  def destroy
    RamenNoodleComment.find_by(id: params[:id], ramen_noodle_id: params[:ramen_noodle_id]).destroy
    redirect_to user_ramen_noodle_path(params[:ramen_noodle_id])
  end

  private

  def ramen_noodle_comment_params
    params.require(:ramen_noodle_comment).permit(:comment)
  end
end

app/controllers/user/ramen_noodles_controller.rb
class User::RamenNoodlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ramen_noodle, only: [:show, :edit, :update, :destroy]

  # レビュー新規投稿ページ
  def new
    @ramen_noodle = RamenNoodle.new
  end

  # レビュー投稿アクション
  def create
    @ramen_noodle = RamenNoodle.new(ramen_noodle_params)
    @ramen_noodle.user_id = current_user.id
    if @ramen_noodle.save(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle.id), notice: "レビューを投稿しました！"
    else
      @ramen_noodles = RamenNoodle.all
      render 'new'
    end
  end

  # レビュー一覧ページ
  def index
    @ramen_noodles = RamenNoodle.page(params[:page]).reverse_order
  end

  # レビュー詳細ページ
  def show
    @ramen_noodle_comment = RamenNoodleComment.new
  end

  # レビュー更新ページ
  def edit
    @user = @ramen_noodle.user
  end

  # レビュー更新アクション
  def update
    if @ramen_noodle.update(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle), notice: "レビュー内容を更新しました！"
    else
      render "edit"
    end
  end

  # レビュー削除アクション
  def destroy
    @ramen_noodle.destroy
    redirect_to user_ramen_noodles_path
  end

  # レビュー検索ページ
  def search
    if params[:address].present?
      @ramen_noodles = RamenNoodle.where('address LIKE ?', "%#{params[:address]}%")
    else
      @ramen_noodles = RamenNoodle.none
    end
  end

  private

  def ramen_noodle_params
    params.require(:ramen_noodle).permit(:title, :address, :image, :name, :price, :body)
  end

  def set_ramen_noodle
    @ramen_noodle = RamenNoodle.find(params[:id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  # マイページ
  def show
    @user = current_user
    @ramen_noodles = @user.ramen_noodles.page(params[:page]).reverse_order
  end

  # 登録情報編集ページ
  def edit
    @user = current_user
  end

  # 更新アクション
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to user_user_path
    else
      render "edit"
    end
  end

  # 退会アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/ramen_noodle_comments_helper.rb
module User::RamenNoodleCommentsHelper
end

app/helpers/user/ramen_noodles_helper.rb
module User::RamenNoodlesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/views/user/users/edit.html.erb
<% provide(:title, "登録情報編集") %>
<h2>登録情報編集</h2>

<%= form_for(@user, html: {class: "form-horizontal"}, url: user_user_path, method: :PUT) do |f| %>

<% if @user.errors.any? %>
<div id="error_explanation">
  <h3><%= @user.errors.count %>件のエラーが発生しました</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group row">
  <%= f.label :"名前", class: "col-xs-12 col-sm-3 col-form-label" %>
  <div class="col-xs-7 col-sm-2">
    <%= f.text_field :name, autofocus: true, placeholder: "（名前）", class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <%= f.label :"メールアドレス", class: "col-xs-12 col-sm-3 col-form-label" %>
  <div class="col-xs-10 col-sm-4">
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "メールアドレス", class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <%= f.label :"年齢", class: "col-xs-12 col-sm-3 col-form-label" %>
  <div class="col-xs-6 col-sm-4">
    <%= f.text_field :age, autofocus: true, placeholder: "年齢", class: "form-control" %>
  </div>
</div>

<div class="actions text-center col-sm-offset-7">
  <%= f.submit "編集内容を保存する", class: "btn btn-primary" %>
</div>
<% end %>

<div class="actions text-center col-sm-offset-7">
  <%= link_to "退会する",user_user_path(current_user.id), class: "btn btn-danger destroy-user",method: :delete %>
</div>

app/views/user/users/show.html.erb
<% provide(:title, "マイページ") %>
<div id="error_explanation">
  <%= flash[:alert] %>
</div>

<h2>マイページ</h2>
<div class="row">
  <div class="col-xs-12 col-sm-7">
    <h4>
      <strong>登録情報</strong>
    </h4>

    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="active col-xs-3 col-sm-4">氏名</td>
          <td class="col-xs-"><%= @user.name %></td>
        </tr>

        <tr>
          <td class="active">年齢</td>
          <td><%= @user.age %></td>
        </tr>

        <tr>
          <td class="active">性別</td>
          <td><% if @user.gender == "male" %>
            男性
            <% else %>
            女性
            <% end %>
          </td>
        </tr>

        <tr>
          <td class="active">メールアドレス</td>
          <td class=""><%= @user.email %></td>
        </tr>

        <tr>
          <td class="active">パスワード</td>
          <td class=""><%= link_to "パスワードを変更する", edit_user_registration_path %>
          </td>
        </tr>
      </tbody>
    </table>

    <div>
      <%= link_to "登録情報を編集する", edit_user_user_path, class: "btn btn-primary pull-right" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h2><%= @user.name %>さんのレビュー一覧</h2>
    <table class="table">
      <thead>
        <tr>
          <th>店名</th>
          <th>商品名</th>
          <th>レビュー</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @ramen_noodles.each do |ramen_noodle| %>
        <tr>
          <td><%= ramen_noodle.title %></td>
          <td><%= link_to ramen_noodle.name, user_ramen_noodle_path(ramen_noodle) %></td>
          <td><%= ramen_noodle.body %></td>
          <td>
            <% if ramen_noodle.favorited_by?(current_user) %>
            <%= link_to user_ramen_noodle_favorites_path(ramen_noodle), method: :delete do %>
            <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
            <%= ramen_noodle.favorites.count %>
            <% end %>
            <% else %>
            <%= link_to user_ramen_noodle_favorites_path(ramen_noodle), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
            <%= ramen_noodle.favorites.count %>
            <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to "#{ramen_noodle.ramen_noodle_comments.count} 件のコメント", user_ramen_noodle_path(ramen_noodle.id) %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @ramen_noodles %>
  </div>
</div>