config/routes.rb
Rails.application.routes.draw do
  get  'inquiries/index'    => 'inquiries#index'
  post 'inquiries/confirm'  => 'inquiries#confirm'
  post 'inquiries/thanks'   => 'inquiries#thanks'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  # user
  namespace :user do
    resources :users
    resources :ramen_noodles do
      resources :ramen_noodle_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      get :search, on: :collection
    end
  end

  root "user/homes#top"
  get  "ramen_noodles"  => "ramen_noodles#index"
  get  "about"          => "user/homes#about"

  # admin
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :ramen_noodles, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_noodle
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => '名前を入力してください' }
  validates :email, :presence => { :message => 'メールアドレスを入力してください' }

  require 'active_model'

  class Person
    include ActiveModel::Validations
  end
end

app/models/ramen_noodle.rb
class RamenNoodle < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  attachment :image
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, :address, :name, :price, :body, :image, presence: true
  validates :price, numericality: true
end

app/models/ramen_noodle_comment.rb
class RamenNoodleComment < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_noodle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ramen_noodles, dependent: :destroy
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, :gender, :age, presence: true
  validates :age, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age])
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  # お問い合わせ画面
  def index
    @inquiry = Inquiry.new
    render 'index'
  end

  # お問い合わせ確認画面
  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      render 'confirm'
    else
      render 'index'
    end
  end

  # お問い合わせ完了通知画面
  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
    render 'thanks'
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # トップページ
  def top
    @all_ranks = RamenNoodle.find(Favorite.group(:ramen_noodle_id).order('count(ramen_noodle_id) desc').limit(3).pluck(:ramen_noodle_id))
  end

  # aboutページ
  def about
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  # マイページ
  def show
    @user = current_user
    @ramen_noodles = @user.ramen_noodles.page(params[:page]).reverse_order
  end

  # 登録情報編集ページ
  def edit
    @user = current_user
  end

  # 更新アクション
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to user_user_path
    else
      render "edit"
    end
  end

  # 退会アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/ramen_noodles_helper.rb
module User::RamenNoodlesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "管理者ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "管理者新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れの方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin">
        <% else %>
        </a>
        <a class="navbar-brand" href="/">
        <% end %>
        </a>

        <div class="shopname pull-left">
          <% if admin_signed_in? %>
          <a href="/admin">
          <% else %>
          <a href="/">
            <% end %>
            <p class="shopname1">ラーメンのレビュー投稿サイト</p>
            <p class="shopname2">Ramen Japan</p>
          </a>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="navbarEexample7">
        <ul class="nav navbar-nav navbar-left"></ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="btn"><%= link_to "マイページ", user_user_path(:id) %></li>
          <li class="btn"><%= link_to "レビュー一覧", user_ramen_noodles_path %></li>
          <li class="btn"><%= link_to "レビュー検索", search_user_ramen_noodles_path, method: :get %></li>
          <li class="btn"><%= link_to "レビュー投稿", new_user_ramen_noodle_path %></li>
          <li class="btn"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

          <% elsif admin_signed_in? %>
          <li class="btn"><%= link_to "ユーザー一覧", admin_users_path %></li>
          <li class="btn"><%= link_to "レビュー一覧", admin_ramen_noodles_path %></li>
          <li class="btn"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>

          <% else %>
          <li class="btn"><%= link_to "About", about_path %></li>
          <li class="btn"><%= link_to "新規登録", new_user_registration_path %></li>
          <li class="btn"><%= link_to "ユーザーログイン", new_user_session_path %></li>
          <li class="btn"><%= link_to "管理者ログイン", new_admin_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>RamenJapan</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container main">
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>

  <footer class="fixed-bottom navbar-fixed-bottom">
    <div class="container">
      <p class="btn btn-default pull-right"><%= link_to "お問い合わせはこちら", inquiries_index_path %></p>
      <p class="pull-left copyright">© All rights reserved by tosi Company</p>
    </div>
  </footer>
</body>
</html>