config/routes.rb
Rails.application.routes.draw do
  get  'inquiries/index'    => 'inquiries#index'
  post 'inquiries/confirm'  => 'inquiries#confirm'
  post 'inquiries/thanks'   => 'inquiries#thanks'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  # user
  namespace :user do
    resources :users
    resources :ramen_noodles do
      resources :ramen_noodle_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      get :search, on: :collection
    end
  end

  root "user/homes#top"
  get  "ramen_noodles"  => "ramen_noodles#index"
  get  "about"          => "user/homes#about"

  # admin
  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :destroy]
    resources :ramen_noodles, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ramen_noodle.rb
class RamenNoodle < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  attachment :image
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, :address, :name, :price, :body, :image, presence: true
  validates :price, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ramen_noodles, dependent: :destroy
  has_many :ramen_noodle_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, :gender, :age, presence: true
  validates :age, numericality: true
end

app/controllers/admin/ramen_noodles_controller.rb
class Admin::RamenNoodlesController < ApplicationController
  before_action :authenticate_admin!

  # レビュー一覧ページ
  def index
    @ramen_noodles = RamenNoodle.page(params[:page]).reverse_order
  end

  # レビュー詳細ページ
  def show
    @ramen_noodle = RamenNoodle.find(params[:id])
  end

  # レビュー削除アクション
  def destroy
    @ramen_noodle = RamenNoodle.find(params[:id])
    @ramen_noodle.destroy
    redirect_to admin_ramen_noodles_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  # ユーザー一覧ページ
  def index
    @users = User.page(params[:page]).per(10)
  end

  # ユーザー詳細ページ
  def show
    @user = User.find(params[:id])
  end

  # ユーザー削除アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  # いいねを付ける
  def create
    ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    favorite = current_user.favorites.new(ramen_noodle_id: ramen_noodle.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  # いいねの取り消し
  def destroy
    ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    favorite = current_user.favorites.find_by(ramen_noodle_id: ramen_noodle.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  # トップページ
  def top
    @all_ranks = RamenNoodle.find(Favorite.group(:ramen_noodle_id).order('count(ramen_noodle_id) desc').limit(3).pluck(:ramen_noodle_id))
  end

  # aboutページ
  def about
  end
end

app/controllers/user/ramen_noodle_comments_controller.rb
class User::RamenNoodleCommentsController < ApplicationController
  before_action :authenticate_user!

  # コメントの作成
  def create
    @ramen_noodle = RamenNoodle.find(params[:ramen_noodle_id])
    comment = current_user.ramen_noodle_comments.new(ramen_noodle_comment_params)
    comment.ramen_noodle_id = @ramen_noodle.id
    comment.save
    redirect_to user_ramen_noodle_path(@ramen_noodle)
  end

  # コメントの削除
  def destroy
    RamenNoodleComment.find_by(id: params[:id], ramen_noodle_id: params[:ramen_noodle_id]).destroy
    redirect_to user_ramen_noodle_path(params[:ramen_noodle_id])
  end

  private

  def ramen_noodle_comment_params
    params.require(:ramen_noodle_comment).permit(:comment)
  end
end

app/controllers/user/ramen_noodles_controller.rb
class User::RamenNoodlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ramen_noodle, only: [:show, :edit, :update, :destroy]

  # レビュー新規投稿ページ
  def new
    @ramen_noodle = RamenNoodle.new
  end

  # レビュー投稿アクション
  def create
    @ramen_noodle = RamenNoodle.new(ramen_noodle_params)
    @ramen_noodle.user_id = current_user.id
    if @ramen_noodle.save(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle.id), notice: "レビューを投稿しました！"
    else
      @ramen_noodles = RamenNoodle.all
      render 'new'
    end
  end

  # レビュー一覧ページ
  def index
    @ramen_noodles = RamenNoodle.page(params[:page]).reverse_order
  end

  # レビュー詳細ページ
  def show
    @ramen_noodle_comment = RamenNoodleComment.new
  end

  # レビュー更新ページ
  def edit
    @user = @ramen_noodle.user
  end

  # レビュー更新アクション
  def update
    if @ramen_noodle.update(ramen_noodle_params)
      redirect_to user_ramen_noodle_path(@ramen_noodle), notice: "レビュー内容を更新しました！"
    else
      render "edit"
    end
  end

  # レビュー削除アクション
  def destroy
    @ramen_noodle.destroy
    redirect_to user_ramen_noodles_path
  end

  # レビュー検索ページ
  def search
    if params[:address].present?
      @ramen_noodles = RamenNoodle.where('address LIKE ?', "%#{params[:address]}%")
    else
      @ramen_noodles = RamenNoodle.none
    end
  end

  private

  def ramen_noodle_params
    params.require(:ramen_noodle).permit(:title, :address, :image, :name, :price, :body)
  end

  def set_ramen_noodle
    @ramen_noodle = RamenNoodle.find(params[:id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  # マイページ
  def show
    @user = current_user
    @ramen_noodles = @user.ramen_noodles.page(params[:page]).reverse_order
  end

  # 登録情報編集ページ
  def edit
    @user = current_user
  end

  # 更新アクション
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "登録情報を変更しました"
      redirect_to user_user_path
    else
      render "edit"
    end
  end

  # 退会アクション
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/ramen_noodles_helper.rb
module Admin::RamenNoodlesHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/ramen_noodle_comments_helper.rb
module User::RamenNoodleCommentsHelper
end

app/views/user/ramen_noodles/edit.html.erb
<div class="container">
	<div class="row">

		<h2>レビュー編集</h2>
		<%= form_for(@ramen_noodle, url:user_ramen_noodle_path) do |f| %>
		<% if @ramen_noodle.errors.any? %>
		<h3><%= @ramen_noodle.errors.count %>件のエラーがあるので更新できませんでした</h3>
		<% @ramen_noodle.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
		<% end %>

		<div class="ramen_noodle_image col-xs-3">
			<%= attachment_image_tag @ramen_noodle, :image, :fill, 250, 250, fallback: "no_image.png", size:"250x250" %>
		<%= f.attachment_field :image %>
		</div>

		<div class="col-xs-9">
			<%= f.label :"商品名", class: "col-xs-12 col-sm-3 col-form-label" %>
			<div class="">
				<%= f.text_field :name, autofocus: true, placeholder: "（商品名）", class: "form-control" %>
			</div>
		</div>

		<div class="col-xs-9">
			<%= f.label :"値段", class: "col-xs-12 col-sm-3 col-form-label" %>
			<div class="">
				<%= f.text_field :price, autofocus: true, placeholder: "（値段）", class: "form-control" %>
			</div>
		</div>

		<div class="col-xs-9">
			<%= f.label :"店名", class: "col-xs-12 col-sm-3 col-form-label" %>
			<div class="">
				<%= f.text_field :title, autofocus: true, placeholder: "（店名）", class: "form-control" %>
			</div>
		</div>

		<div class="col-xs-9">
			<%= f.label :"住所", class: "col-xs-12 col-sm-3 col-form-label" %>
			<div class="">
				<%= f.text_field :address, autofocus: true, placeholder: "（住所）", class: "form-control" %>
			</div>
		</div>

		<div class="col-xs-9">
			<%= f.label :"レビュー", class: "col-xs-12 col-sm-3 col-form-label" %>
			<div class="">
				<%= f.text_area :body, autofocus: true, placeholder: "（レビュー）", class: "form-control" %>
			</div>
		</div>

		<div class="actions pull-right">
			<%= f.submit 'レビューを変更する', class: "btn btn-primary" %>
			<%= link_to 'レビューを削除する', user_ramen_noodle_path(@ramen_noodle.id),method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger destroy_user_ramen_noodle_#{@ramen_noodle.id}" %>
		</div>
		<% end %>

	</div>
</div>

app/views/user/ramen_noodles/index.html.erb
<div class="container">
	<div class="row">

		<h2>レビュー一覧</h2>
		<table class="table table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>店名</th>
					<th>商品名</th>
					<th>ユーザー</th>
					<th></th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<% @ramen_noodles.each do |ramen_noodle| %>
					<td><%= attachment_image_tag ramen_noodle, :image, :fill, 250, 250, fallback: "no_image.png", size:"250x250" %></td>
					<td><%= ramen_noodle.title %></td>
					<td><%= link_to ramen_noodle.name, user_ramen_noodle_path(ramen_noodle) %></td>
					<td><%= ramen_noodle.user.name %></td>

					<td>
						<% if ramen_noodle.favorited_by?(current_user) %>
						<%= link_to user_ramen_noodle_favorites_path(ramen_noodle), method: :delete do %>
						<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						<%= ramen_noodle.favorites.count %>
						<% end %>
						<% else %>
						<%= link_to user_ramen_noodle_favorites_path(ramen_noodle), method: :post do %>
						<i class="fa fa-heart" aria-hidden="true"></i>
						<%= ramen_noodle.favorites.count %>
						<% end %>
						<% end %>
					</td>

					<td>
						<%= link_to "#{ramen_noodle.ramen_noodle_comments.count} 件のコメント", user_ramen_noodle_path(ramen_noodle.id) %>
					</td>

				</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>
<%= paginate @ramen_noodles %>

app/views/user/ramen_noodles/new.html.erb
<div class="container">
	<div class="row">

		<h2>レビュー投稿はこちら</h2>
		<%= form_for @ramen_noodle, url: user_ramen_noodles_path, class: "form-inline" do |f| %>
		<% if @ramen_noodle.errors.any? %>
		<h3><%= @ramen_noodle.errors.count %>件のエラーがあるのでレビューを投稿できませんでした</h3>
		<% @ramen_noodle.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
		<% end %>

		<div class="form-group col-xs-4">
			<div class="item-image">
				<%= attachment_image_tag @ramen_noodle, :image, class: "img-square", fallback: "no_image.png", size:"300x300" %>
			</div>
			<%= f.attachment_field :image, placeholder: "画像" %>
		</div>

		<div class="col-xs-8">
			<div class="field">
				<%= f.label :"店名" %>
				<%= f.text_field :title, class: "col-xs-12 ramen_noodle_title" %>
			</div>

			<div class="field">
				<%= f.label :"住所" %>
				<%= f.text_field :address, class: "col-xs-12 ramen_noodle_address" %>
			</div>

			<div class="field">
				<%= f.label :"商品名" %>
				<%= f.text_field :name, class: "col-xs-12 ramen_noodle_name" %>
			</div>

			<div class="field">
				<%= f.label :"値段" %>
				<%= f.text_field :price, class: "col-xs-12 ramen_noodle_price" %>
			</div>

			<div class="field">
				<%= f.label :"レビュー" %>
				<%= f.text_area :body, class: "col-xs-12 ramen_noodle_body" %>
			</div>

			<div class="field pull-right">
				<%= f.submit "投稿する", class: "btn btn-success" %>
			</div>
		</div>
		<% end %>

	</div>
</div>

<!-- 画像プレビュー機能 -->
<script>
	$(function(){
  // inputのidから情報の取得
  $('#ramen_noodle_image').on('change', function (e) {
// ここから既存の画像のurlの取得
var reader = new FileReader();
reader.onload = function (e) {
	$(".image").attr('src', e.target.result);
}
// ここまで
  reader.readAsDataURL(e.target.files[0]); //取得したurlにアップロード画像のurlを挿入
});
});
</script>

app/views/user/ramen_noodles/search.html.erb
<h2>レビュー検索(住所を入力してください)</h2>
<%= form_with url: search_user_ramen_noodles_path, method: :get, local: true do |f| %>
<%= f.text_field :address %>
<%= f.submit :検索する %>
<% end %>

<h4>検索した住所が含まれるレビュー一覧</h4>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>店名</th>
      <th>住所</th>
      <th>商品名</th>
      <th>レビュー</th>
    </tr>
  </thead>

  <tbody>
    <% @ramen_noodles.each do |ramen_noodle| %>
    <tr>
      <td><%= link_to ramen_noodle.title, user_ramen_noodle_path(ramen_noodle) %></td>
      <td><%= ramen_noodle.address %></td>
      <td><%= ramen_noodle.name %></td>
      <td><%= ramen_noodle.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/user/ramen_noodles/show.html.erb
<div class="container">
	<div class="row">
		<h2>レビュー詳細</h2>

		<div class="col-xs-4">
			<%= attachment_image_tag(@ramen_noodle, :image, :fill, 380, 380) %>
		</div>

		<div class="col-xs-8">
			<table class="table table-bordered">
				<tbody>
					<tr>
						<td class="active">店名</td>
						<td><%= @ramen_noodle.title %></td>
					</tr>

					<tr>
						<td class="active">住所</td>
						<td>
							<%= @ramen_noodle.address %>
							<script type="text/javascript">
								function initMap() {
									var test ={lat: <%= @ramen_noodle.latitude %>, lng: <%= @ramen_noodle.longitude %>};
									var map = new google.maps.Map(document.getElementById('map'), {
										zoom: 15,
										center: test
									});
									var transitLayer = new google.maps.TransitLayer();
									transitLayer.setMap(map);

									var contentString = '住所:<%= @ramen_noodle.address %>';
									var infowindow = new google.maps.InfoWindow({
										content: contentString
									});

									var marker = new google.maps.Marker({
										position:test,
										map: map,
										title: contentString
									});

									marker.addListener('click', function() {
										infowindow.open(map, marker);
									});
								}
							</script>

							<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
							</script>

							<style type="text/css">
								#map { height: 250px; width: 100%;}
							</style>

							<div id="map"></div>
						</td>
					</tr>

					<tr>
						<td class="active col-xs-3 col-sm-4">商品名</td>
						<td><%= @ramen_noodle.name %></td>
					</tr>

					<tr>
						<td class="active">値段</td>
						<td><%= @ramen_noodle.price %>円(税込)</td>
					</tr>

					<tr>
						<td class="active">レビュー</td>
						<td><%= @ramen_noodle.body %></td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="pull-right">
			<% if @ramen_noodle.user == current_user %>
			<%= link_to "レビュー内容編集", edit_user_ramen_noodle_path(@ramen_noodle), class: "btn-sm btn-primary edit_ramen_noodle_#{@ramen_noodle.id}" %>
			<% end %>
		</div>

		<i class="fa fa-comment"></i>
		<%= @ramen_noodle.ramen_noodle_comments.count %>

		<% if @ramen_noodle.favorited_by?(current_user) %>
		<%= link_to user_ramen_noodle_favorites_path(@ramen_noodle), method: :delete do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		<%= @ramen_noodle.favorites.count %>
		<% end %>
		<% else %>
		<%= link_to user_ramen_noodle_favorites_path(@ramen_noodle), method: :post do %>
		<i class="fa fa-heart" aria-hidden="true"></i>
		<%= @ramen_noodle.favorites.count %>
		<% end %>
		<% end %>

		<div class="comment-list bt style-2" id="comments">
			<div class="float-wrapper">
				<h2 class="comment-count"><%= @ramen_noodle.ramen_noodle_comments.count %>件のコメントがあります</h2>
			</div>
		</div>

		<% @ramen_noodle.ramen_noodle_comments.each do |ramen_noodle_comment| %>
		<div class="comment-body bb">
			<div class="comment-text">
				<div class="comment-author clearfix">
					<%= ramen_noodle_comment.user.name %></a>
					<span class="comment-meta">
						<span class="comment-date"><%= ramen_noodle_comment.created_at.strftime('%Y/%m/%d') %></span>
					</span>
				</div>
				<div class="comment-entry">
					<%= ramen_noodle_comment.comment %>
				</div>
				<% if ramen_noodle_comment.user == current_user %>
				<div>
					<%= link_to "コメント削除", user_ramen_noodle_ramen_noodle_comment_path(ramen_noodle_comment.ramen_noodle, ramen_noodle_comment), method: :delete, class: "btn btn-danger" %>
				</div>
				<% end %>
			</div>
		</div>
		<% end %>

		<%= form_for [@ramen_noodle, @ramen_noodle_comment], url: user_ramen_noodle_ramen_noodle_comments_path(@ramen_noodle.id) do |f| %>
		<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに入力してください" %>
		<%= f.submit "コメントを投稿する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
		<% end %>

	</div>
</div>